USE [master]
GO

/****** Object:  Database [MAMS]    Script Date: 8/30/2024 3:05:45 PM ******/
CREATE DATABASE [MAMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MAMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BackUp-30-Aug-2024.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MAMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BackUp-30-Aug-2024_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MAMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MAMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MAMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MAMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MAMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MAMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [MAMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MAMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MAMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MAMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MAMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MAMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MAMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MAMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MAMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MAMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MAMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MAMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MAMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MAMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MAMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MAMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MAMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MAMS] SET RECOVERY FULL 
GO

ALTER DATABASE [MAMS] SET  MULTI_USER 
GO

ALTER DATABASE [MAMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MAMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MAMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MAMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MAMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MAMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MAMS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MAMS] SET  READ_WRITE 
GO

